version: "3.8"

services:
  rag-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-dashboard
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - shared_network

networks:
  shared_network:
    external: true